require("plugins")

require("vimconf.navigation")
require("vimconf.style")
require("vimconf.lsp")

require("pluginconf.gruvbox_conf")
require("pluginconf.telescope_conf")
--require("pluginconf.bettertabs_conf")
--require("pluginconf.bufferline_conf")
require("pluginconf.lualine_conf")
require("pluginconf.compiler_conf")
require("pluginconf.neoscroll_conf")
require("pluginconf.neotree_conf")
require("pluginconf.lazygit_conf")
